name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Check Ruby Version
      run: ruby -v

    - name: Install Jekyll, Bundler and FFI
      run: |
        gem update --system
        gem install bundler -v 2.2.33
        gem install ffi -v 1.17.1
        gem install jekyll
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build --destination _site

    - name: Inject Firebase API Key
      run: echo "window.FIREBASE_API_KEY = '${{ secrets.FIREBASE_API_KEY }}';" > _site/firebase-config.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site